"""empty message

Revision ID: 0c22470a56de
Revises: 64a70a7aab8b
Create Date: 2024-07-10 00:03:11.273603

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c22470a56de'
down_revision = '64a70a7aab8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_tmp_dataset',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('tmp_dataset_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name='conv_tmp_dataset_binding_pkey')
    )
    with op.batch_alter_table('conversation_tmp_dataset', schema=None) as batch_op:
        batch_op.create_index('conversation_tmp_dataset_conversation_id_idx', ['conversation_id'], unique=False)
        batch_op.create_index('conversation_tmp_dataset_tmp_dataset_id_idx', ['tmp_dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_tmp_dataset', schema=None) as batch_op:
        batch_op.drop_index('conversation_tmp_dataset_tmp_dataset_id_idx')
        batch_op.drop_index('conversation_tmp_dataset_conversation_id_idx')

    op.drop_table('conversation_tmp_dataset')
    # ### end Alembic commands ###
